let products = [
    {
        id: 1001,
        subject: 'Math',
        description: 'Fundamental concepts of mathematics.',
        location: 'Dubai, UAE',
        price: 100,
        image: './images/Logo.png',
        rating: 3,
        availableInventory: 10,
    },
    {
        id: 1002,
        subject: 'ChatGPT MasterClass',
        description: 'Learn advanced techniques for ChatGPT.',
        location: 'Bur Dubai, UAE',
        price: 120,
        image: './images/chatgpt.jpeg',
        rating: 4,
        availableInventory: 10,
    },
    {
        id: 1003,
        subject: 'Sports Photography',
        description: 'Master photography at sports events.',
        location: 'Dubai Sports City, UAE',
        price: 150,
        image: './images/photography.jpeg',
        rating: 4,
        availableInventory: 10,
    },
    {
        id: 1004,
        subject: 'Art and Design',
        description: 'Explore your creativity in design.',
        location: 'Abu Dhabi, UAE',
        price: 110,
        image: './images/art.webp',
        rating: 5,
        availableInventory: 10,
    },
    {
        id: 1005,
        subject: 'Python Programming',
        description: 'Introduction to Python programming for beginners.',
        location: 'Sharjah, UAE',
        price: 130,
        image: './images/python.webp',
        rating: 4,
        availableInventory: 10,
    },
    {
        id: 1006,
        subject: 'Digital Marketing',
        description: 'Master the basics of digital marketing.',
        location: 'Dubai, UAE',
        price: 140,
        image: './images/digital.jpeg',
        rating: 5,
        availableInventory: 10,
    },
    {
        id: 1007,
        subject: 'Web Development',
        description: 'Learn to build websites using HTML, CSS, and JavaScript.',
        location: 'Dubai Media City, UAE',
        price: 160,
        image: './images/webdev.webp',
        rating: 3,
        availableInventory: 10,
    },
    {
        id: 1008,
        subject: 'Music Production',
        description: 'Basics of music production and sound engineering.',
        location: 'Abu Dhabi, UAE',
        price: 125,
        image: './images/music.webp',
        rating: 4,
        availableInventory: 10,
    },
    {
        id: 1009,
        subject: 'Creative Writing',
        description: 'Enhance your writing skills and storytelling.',
        location: 'Al Ain, UAE',
        price: 115,
        image: './images/writting.webp',
        rating: 4,
        availableInventory: 10,
    },
    {
        id: 1010,
        subject: 'Yoga and Mindfulness',
        description: 'Learn yoga and mindfulness techniques.',
        location: 'Ras Al Khaimah, UAE',
        price: 90,
        image: './images/yoga.webp',
        rating: 5,
        availableInventory: 10,
    },
];
